### PR TITLE
Fixed index out-of-range for newly generated wallets

### PR DESCRIPTION
**Pull request by jasonbcox**
Tried cashshuffle on a brand new wallet to find that shuffle would constantly crash until initial funds were confirmed.  Tested manually to confirm the fix (there's no test coverage for this portion of code by the looks of it)

### CODE REVIEW

**Comment by jasonbcox** [comment]
Fixes #33

**Comment by jasonbcox** [comment]
Looks like the merge conflict was caused because a fix was pushed around the time I made the PR: 209fd458821af98077fd07ee95c9ee8dae4c560b  The fix doesn't include changes to the other _as_string method though.

**Comment by jasonbcox** [comment]
Updated the diff to include the other method (which appears to not be used).

**Comment by clifordsymack** [comment]
@jasonbcox Thanks a lot for your activity! Join the project!

**Pull request closed without merging**
